clusterName: ${cluster_name}

region: ${region}

vpcId: ${vpc_id}

serviceAccount:
  create: true
  name: aws-load-balancer-controller
  annotations:
    eks.amazonaws.com/role-arn: ${role_arn}

defaultLoadBalancerScheme: internet-facing

ingressClassParams:
  spec:
    inboundCIDRs:
%{ for cidr in inbound_cidrs ~}
      - ${cidr}
%{ endfor ~}
    subnets:
      ids: ${subnet_ids}