variable "tfc_organization" {
  type        = string
  description = "TFC organization name"
}

variable "tfc_base_workspace" {
  type        = string
  description = "TFC base workspace name"
  default     = "txc-base"
}

variable "tfc_kubernetes_workspace" {
  type        = string
  description = "TFC kubernetes workspace name"
  default     = "txc-kubernetes"
}

variable "aws_region" {
  description = "AWS region where resources will be created"
  type        = string
  default     = "us-east-1"
}

variable "environment" {
  description = "Environment name (e.g., dev, staging, prod)"
  type        = string
  default     = "dev"

  validation {
    condition     = contains(["dev", "staging", "prod"], var.environment)
    error_message = "Environment must be dev, staging, or prod."
  }
}

variable "inbound_cidrs_for_lbs" {
  description = "CIDR blocks allowed to access load balancers"
  type        = list(string)
  default     = []
}

variable "project_name" {
  description = "Project name used for resource naming and tagging"
  type        = string
  default     = "infrastructure-agent"
}

variable "vault_token" {
  type        = string
  description = "Vault token"
  sensitive   = true
}

variable "client_agents" {
  type = map(object({
    k8s_namespace = string,
    claims        = map(string),
  }))
  description = "Client agents that request actor tokens. Must include Kubernetes namespace and claims added to token."
}

variable "oauth_token_exchange_secrets_path" {
  type        = string
  description = "Vault path for oauth token exchange secrets"
  default     = "sts"
}

variable "vault_private_endpoint" {
  type        = string
  description = "Private endpoint for Vault. Used for issuer for OIDC provider and verifying JWTs"
  default     = "https://vault-ui.vault:8200"
}

variable "mcp_context_forge_jwt_secret" {
  type        = string
  description = "Generated by MCP Context Forge init scripts"
}

variable "mcp_context_forge_auth_encryption_secret" {
  type        = string
  description = "Generated by MCP Context Forge init scripts"
}
