FROM langflowai/langflow:1.9.2-amd64

USER root

RUN apt update && apt install -y libgl1 libglib2.0-0 && uv pip install langflow[docling] && rm -rf /var/lib/apt/lists/*

USER user

WORKDIR /app

CMD ["langflow" "run"]