#!/usr/bin/env bash
# Exports non-sensitive environment variables required for tests and local tooling.
# Run this after all Terraform workspaces have been applied and Vault has been initialized.
#
# Usage:
#   source scripts/export-env.sh
#
# Note: VAULT_TOKEN and MCPGATEWAY_BEARER_TOKEN are NOT set here because they contain
# credentials that must be supplied separately:
#   - VAULT_TOKEN: read from secrets/vault-init.json (generated by scripts/vault-init.sh)
#   - MCPGATEWAY_BEARER_TOKEN: generate a new API token from the MCP Context Forge admin UI
#     and set it manually before running tests.

export VAULT_ADDR=$(cd terraform/kubernetes && terraform output -raw vault_endpoint)
export VAULT_SKIP_VERIFY=true
export KUBERNETES_CONTEXT=$(kubectl config current-context)
export MCPGATEWAY_URL=$(cd terraform/mcp-context-forge && terraform output -raw mcp_context_forge_url)
export SUMMARIZER_URL=$(cd terraform/summarizer && terraform output -raw summarizer_agent_url)
